const authorityPage = [
        {
            "title":"系统设置",
            "key":"m:setting",
            "type":"0",
            "children":[
                {
                    "title":"应用商城",
                    "key":"m:appstore",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"权限设置",
                    "key":"m:permissions",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"流量统计",
                    "key":"m:statistics",
                    "type":"0",
                    "children":[
                        {
                            "title":"访问统计",
                            "key":"m:statistics:visit",
                            "type":"0",
                            "children":null
                        },
                        {
                            "title":"来路域名",
                            "key":"m:statistics:domain",
                            "type":"0",
                            "children":null
                        },
                        {
                            "title":"搜索引擎",
                            "key":"m:statistics:engine",
                            "type":"0",
                            "children":null
                        },
                        {
                            "title":"IP统计",
                            "key":"m:statistics:ip",
                            "type":"0",
                            "children":null
                        }
                    ]
                },
                {
                    "title":"采集管理",
                    "key":"m:collection",
                    "type":"0",
                    "children":[
                        {
                            "title":"节点管理",
                            "key":"m:collection:node",
                            "type":"0",
                            "children":null
                        },
                        {
                            "title":"内容管理",
                            "key":"m:collection:article",
                            "type":"0",
                            "children":null
                        }
                    ]
                },
                {
                    "title":"数据库",
                    "key":"m:mysql",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"模型管理",
                    "key":"m:customize",
                    "type":"0",
                    "children":[
                        {
                            "title":"字段管理",
                            "key":"m:customize:field",
                            "type":"0",
                            "children":null
                        }
                    ]
                },
                {
                    "title":"登录日志",
                    "key":"m:log",
                    "type":"0",
                    "children":[
                        {
                            "title":"管理员登录日志",
                            "key":"m:log:margin",
                            "type":"0",
                            "children":null
                        },
                        {
                            "title":"用户登录日志",
                            "key":"m:log:user",
                            "type":"0",
                            "children":null
                        }
                    ]
                }
            ]
        },
        {
            "title":"运营中心",
            "key":"m:business",
            "type":"0",
            "children":[
                {
                    "title":"友情链接",
                    "key":"m:link",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"合作伙伴",
                    "key":"m:partner",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"推广管理",
                    "key":"m:spread",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"广告服务",
                    "key":"m:advertisement",
                    "type":"0",
                    "children":[
                        {
                            "title":"新增广告",
                            "key":"m:advertisement:article",
                            "type":"0",
                            "children":null
                        }
                    ]
                }
            ]
        },
        {
            "title":"网站信息",
            "key":"m:site",
            "type":"0",
            "children":[
                {
                    "title":"网站导航",
                    "key":"m:navigation",
                    "type":"0",
                    "children":[
                        {
                            "title":"导航列表",
                            "key":"m:navigation:main",
                            "type":"0",
                            "children":[
                                {
                                    "title":"新增子导航",
                                    "key":"m:navigation:main:child",
                                    "type":"1",
                                    "children":null
                                },
                                {
                                    "title":"删除",
                                    "key":"b:navigation:main:delete",
                                    "type":"1",
                                    "children":null
                                },
                                {
                                    "title":"编辑",
                                    "key":"b:navigation:main:edit",
                                    "type":"1",
                                    "children":null
                                },
                                {
                                    "title":"新增导航",
                                    "key":"m:navigation:main:article",
                                    "type":"0",
                                    "children":null
                                }
                            ]
                        },
                        {
                            "title":"单页列表",
                            "key":"m:navigation:single",
                            "type":"0",
                            "children":[
                                {
                                    "title":"新增单页",
                                    "key":"m:navigation:single:article",
                                    "type":"0",
                                    "children":null
                                }
                            ]
                        }
                    ]
                },
                {
                    "title":"基本信息",
                    "key":"m:basic",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"幻灯片",
                    "key":"m:slideshow",
                    "type":"0",
                    "children":[
                        {
                            "title":"轮播图",
                            "key":"m:slideshow:img",
                            "type":"0",
                            "children":null
                        }
                    ]
                },
                {
                    "title":"静态生成",
                    "key":"m:static",
                    "type":"0",
                    "children":null
                }
            ]
        },
        {
            "title":"频道管理",
            "key":"m:channel",
            "type":"0",
            "children":[
                {
                    "title":"资讯",
                    "key":"m:article",
                    "type":"0",
                    "children":[
                        {
                            "title":"分类管理",
                            "key":"m:article:cate",
                            "type":"0",
                            "children":null
                        },
                        {
                            "title":"文档管理",
                            "key":"m:article:article",
                            "type":"0",
                            "children":null
                        },
                        {
                            "title":"回收站",
                            "key":"m:article:recycle",
                            "type":"0",
                            "children":null
                        }
                    ]
                }
            ]
        },
        {
            "title":"服务中心",
            "key":"m:service",
            "type":"0",
            "children":[
                {
                    "title":"基本信息",
                    "key":"m:service:basic",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"公告信息",
                    "key":"m:service:announcement",
                    "type":"0",
                    "children":[
                        {
                            "title":"发布公告",
                            "key":"m:service:announcement:article",
                            "type":"0",
                            "children":null
                        }
                    ]
                },
                {
                    "title":"在线留言",
                    "key":"m:service:messageBoard",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"意见反馈",
                    "key":"m:service:feedback",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"招贤纳士",
                    "key":"m:service:job",
                    "type":"0",
                    "children":[
                        {
                            "title":"职位管理",
                            "key":"m:service:job:position",
                            "type":"0",
                            "children":null
                        },
                        {
                            "title":"求职简历",
                            "key":"m:service:job:resume",
                            "type":"0",
                            "children":null
                        }
                    ]
                }
            ]
        },
        {
            "title":"用户管理",
            "key":"m:user",
            "type":"0",
            "children":[
                {
                    "title":"用户类型",
                    "key":"m:user:type",
                    "type":"0",
                    "children":[
                        {
                            "title":"用户管理",
                            "key":"m:user:type:list",
                            "type":"0",
                            "children":null
                        }
                    ]
                },
                {
                    "title":"会员权限",
                    "key":"m:user:grade",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"角色权限",
                    "key":"m:user:rolegrade",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"用户等级",
                    "key":"m:user:group",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"积分设置",
                    "key":"m:user:sign",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"用户审核",
                    "key":"m:user:audit",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"用户禁言",
                    "key":"m:user:banuser",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"推荐管理",
                    "key":"m:user:recommend",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"保密问题",
                    "key":"m:user:security",
                    "type":"0",
                    "children":null
                },
                {
                    "title":"主题风格",
                    "key":"m:user:theme",
                    "type":"0",
                    "children":null
                }
            ]
        },
        {
            "title":"更多设置",
            "key":"m:more",
            "type":"0",
            "children":null
        },
        {
            "title":"定义1",
            "key":"m:more1",
            "type":"0",
            "children":null
        },
        {
            "title":"定义2",
            "key":"m:more2",
            "type":"0",
            "children":null
        },
        {
            "title":"定义3",
            "key":"m:more3",
            "type":"0",
            "children":null
        }
    ]

export default authorityPage